### ISSUE TITLE
Disable OS selection menu and change boot order

### ISSUE THREAD

**Issue by Danct12** [danielotero/linux-on-hi10#14]
I don't have Windows anymore, but still have Android, I would like to use rEFInd to boot Android and Arch instead.

I know that you can use a tool by Chuwi themselves to disable it, but I don't want to make a Windows To Go drive, and there's no way to change the boot order.

**Comment by danielotero** [comment]
I was able to disable that menu, but I didn't document the procedure. Now,
I have the menu back again and don't remember how to disable it. Here is
what I know:

The configuration of the Android/Windows menu is stored in the EFI
variables.
The exact EFI variable could be found as a string in the `SwitchNOW`
executable.
I have no clue about the Variable value when the menu is disabled, so we
must find someone who has Windows to reverse-engineer it.

Disclaimer: Modifying EFI variables may, and probably will, render your
device completely unusable. I don't recommend doing this if you have any
kind of affection to the machine.

**Comment by samueldr** [comment]
Hi!

I have those following notes laying around about that. DO NOTE that no warranty is given or implied. I am not an expert, and it could result in the machine being broken (standard disclaimers).

* * *

Disabling the annoying boot menu
================================
As documented, partially, here:
 → https://github.com/RamKromberg/toggleBootSelectVariable/blob/master/toggleBootSelectVariable.c

The values you might want are those:

    $ sudo -i
    # chattr -i /sys/firmware/efi/efivars/BootSelectVariable-944fb13b-773f-4cbb-9c6f-326cebde4c23
    # printf '\x07\x00\x00\x00\x2a\x00\x00\x00' > /sys/firmware/efi/efivars/BootSelectVariable-944fb13b-773f-4cbb-9c6f-326cebde4c23

The `chattr -i` is new-ish and comes from a workaround against bad EFI implementations that bricks computers when variables are accidentally `rm -rf`ed.

**Comment by danielotero** [comment]
It works like a charm! Thanks!

**Comment by Danct12** [comment]
Works like a charm, thank you.

But I still cannot change the UEFI boot order, prehaps it has something to do with BOOTX64.EFI in EFI partitions? I realized that if I set my Grub EFI file name to that it creates another Android-IA in the boot order.

**Comment by iGerman00** [comment]
> $ sudo -i
> # chattr -i /sys/firmware/efi/efivars/BootSelectVariable-944fb13b-773f-4cbb-9c6f-326cebde4c23
> # printf '\x07\x00\x00\x00\x2a\x00\x00\x00' > /sys/firmware/efi/efivars/BootSelectVariable-944fb13b-773f-4cbb-9c6f-326cebde4c23

Worked just as well on my Hi8 Pro! Thanks!!

**Comment by Danct12** [comment]
Also it seems like you can disable the OS selection menu by turning "Fast Boot" option on in the BIOS.

**Comment by Kellwaxx11** [comment]
Hi @samueldr 
thank you for the how to , it worked fine for me on Chuwi Hi8 Air and disabled the touch bootloader

just wondering how to enable the touch bootloader again, I tried changing the part aft "printf" 
"\x07\x00\x00\x00\x00\x00\x00\x00" and
"\x07\x00\x00\x00\x80\x00\x00\x00"

but its not enabled again

apreciate any advice.
thank you

**Comment by samueldr** [comment]
I don't know, the way it would be reverted. There is likely a given value that it uses when enabled.

I believe resetting the UEFI firmware settings should re-enable that menu. Assuming it does, you could dump the value of the EFI var (using e.g. `xxd` or `hexdump`) and share back what it could be set to.

**Comment by Kellwaxx11** [comment]
unfortunatly resetting UEFI firmware didnt work
but i found this forum
https://forum.chuwi.com/t/linux-mint-20-cinnamon-working-perfectly-on-hi12/15041/10

and seems that the 3rd to the last hex is the one to control enabel/disable, at least on my device Hi8 Air
so to the printf command should be (at least for my device, try at your own risk):
- Disabled "\x07\x00\x00\x00\xA8\x00\x00\x00"
- Enabled  "\x07\x00\x00\x00\xA8\x04\x00\x00"

attached is the dmpstore files from EFI shell for both cases
they can be restored with EFI shell command "dmpstore -l filename.dmp"
[disabled.dmp](https://github.com/danielotero/linux-on-hi10/files/14731973/disabled.dmp)
[enabled.dmp](https://github.com/danielotero/linux-on-hi10/files/14731974/enabled.dmp)


what brings the question now, how to change the timeout value, if anyone knows please share.

also if anyone on Linux is interested of replacing this bootloader, I found that "systemd-boot" is a better option instead of GRUB, as it response to the volumne up/down keys as well as power button to select.
maybe other bootloaders does as well, but i havent tried yet.

**Comment by Kellwaxx11** [comment]
i actually found the timeout variable, it is 
"8be4df61-93ca-11d2-aa0d-00e098032b8c-Timeout"
and was able to dmpstore save it from EFI shell
but not sure how to modify it to change the time
this is the 10 sec
[timeout.dmp](https://github.com/danielotero/linux-on-hi10/files/14732080/timeout.dmp)
